# Generated by Django 4.2 on 2023-04-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_tbteammembers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbVoters',
        ),
    ]
